import requests
from behave import *

@given('I request BIS')
def step_given(context, ) :
    pass
      # This was autogenerated using cucumber syntax.
      # Please convert to use regular expressions, as Behave does not currently support Cucumber Expressions

@when('I send a GET request')
def step_when(context, ) :
       url = "https://bug6wxr929.execute-api.eu-west-1.amazonaws.com/Prod/bis?isGenderKnown=true&isBirthdateKnown=true"
       data = {}
       for row in context.table:
            data[row[0]] = row[1]
       context.response = requests.get(url, data=data)

@then ("the response status code should be 200")
def step_impl(context):
    assert context.response.status_code == 200
  